### ISSUE TITLE
406 error why?

### ISSUE THREAD

**Issue by cheemzboi** [AJTimePyro/Crunchyroll-Account-Checker#10]
i got a 406 response code error

**Comment by AJTimePyro** [comment]
Well it's proxyless tool, so it can't be helped. Try to use vpn or external proxies.

**Comment by cheemzboi** [comment]
proxys cant help it much too
figured out the soltuion is using windows api rn

**Comment by cheemzboi** [comment]
your repo helped me thanks for that

**Comment by Bedrock16** [comment]
> your repo helped me thanks for that



> proxys cant help it much too figured out the soltuion is using windows api rn

Can u send example pls??
