### ISSUE TITLE
Entering file name or path issue

### ISSUE THREAD

**Issue by Huzaifa1122334** [AJTimePyro/Crunchyroll-Account-Checker#11]
Sir when i tried to enter name or path of file it show file not found.sir plz help me by telling how to enter file name or path.plz explain with the help of an example....

**Comment by AJTimePyro** [comment]
Well that's weird,
when it asks you the file path, you can drag and drop the file which will automatically paste the path.

**Comment by Huzaifa1122334** [comment]
How can i do the same in android phone brother

**Comment by AJTimePyro** [comment]
then you have no other choice rather than entering filepath along filename
eg, `/storage/emulated/0/Download/file.txt`
something like this
or move your file to account checker tool's folder, this way you just have to enter filename

**Comment by Huzaifa1122334** [comment]
Sir previous issue clear thank you soo much but in most accounts it shows Error in while trying to login HTTP Error 406: Not Acceptable....plz help and kindly explain this there are multiple proxies accounts how can i solve it all....

**Comment by AJTimePyro** [comment]
Well try to use vpn,
since code is not updated from a long time, I think it needs some update which I will update in next month probably.

**Comment by Huzaifa1122334** [comment]
Sir have you the same tool like this for netflix checker if you have send
me commands plz plz plz ....

**Comment by AJTimePyro** [comment]
Nope I don't have.
