### ISSUE TITLE
Giving type-error

### ISSUE THREAD

**Issue by Koneron** [AJTimePyro/Crunchyroll-Account-Checker#16]
when i run the main.py. it gets interrupted while saying

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

this is the whole terminal feed:

Traceback (most recent call last):
  File "d:\Checkers\Crunchyroll-Account-Checker-master\main.py", line 17, in <module>      
    import src.checker
  File "d:\Checkers\Crunchyroll-Account-Checker-master\src\checker.py", line 5, in <module>
    from src import (
  File "d:\Checkers\Crunchyroll-Account-Checker-master\src\proxy.py", line 13, in <module> 
    class Proxy:
  File "d:\Checkers\Crunchyroll-Account-Checker-master\src\proxy.py", line 17, in Proxy    
    proxy_filename : str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

is there something i need to import/download?

**Comment by AJTimePyro** [comment]
which python version are you using?

**Comment by Koneron** [comment]
> which python version are you using?

3.9.13

**Comment by AJTimePyro** [comment]
Upgrade your python version to 3.10 or higher

**Comment by AJTimePyro** [comment]
Or if you don't want to, then [here](https://github.com/AJTimePyro/Crunchyroll-Account-Checker/blob/master/src/proxy.py#L17), remove this `: str | None` from the code

**Comment by Koneron** [comment]
I got it working now TYSM man

**Comment by Koneron** [comment]
also what can i do about the error 406? It seems like I'm restricted for too many entries

**Comment by AJTimePyro** [comment]
Use proxies, and ignore the 406 error and other errors.
