### ISSUE TITLE
i can't use it with proxy

### ISSUE THREAD

**Issue by Zackenx** [AJTimePyro/Crunchyroll-Account-Checker#17]
Proxy is not working while login  <urlopen error [Errno 11001] getaddrinfo failed>

**Comment by AJTimePyro** [comment]
Proxy might be dead

**Comment by AJTimePyro** [comment]
Try default proxy list, in which tool automatically fetches proxies(most of them are dead but some will work) and you need to have patience.
Or Alternatively use without proxy and connect to any vpn

**Comment by AJTimePyro** [comment]
No response, closing the issue. You can alway reopen the issue
