### ISSUE TITLE
Error trying to start main.py

### ISSUE THREAD

**Issue by Certiax** [AJTimePyro/Crunchyroll-Account-Checker#18]
Exception has occurred: UnicodeDecodeError
'charmap' codec can't decode byte 0x8f in position 2995: character maps to <undefined>
  File "C:\Users\KSAXp\Downloads\Compressed\Crunchyroll-Account-Checker-1.0\Crunchyroll-Account-Checker-1.0\src\checker.py", line 59, in _checker
    for line in file.readlines():
                ^^^^^^^^^^^^^^^^
  File "C:\Users\KSAXp\Downloads\Compressed\Crunchyroll-Account-Checker-1.0\Crunchyroll-Account-Checker-1.0\src\checker.py", line 55, in create
    self._checker()
  File "C:\Users\KSAXp\Downloads\Compressed\Crunchyroll-Account-Checker-1.0\Crunchyroll-Account-Checker-1.0\main.py", line 38, in main
    src.checker.CrunchyrollChecker.create(filename, proxy_filename)
  File "C:\Users\KSAXp\Downloads\Compressed\Crunchyroll-Account-Checker-1.0\Crunchyroll-Account-Checker-1.0\main.py", line 45, in <module>
    main()
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2995: character maps to <undefined>

**Comment by Certiax** [comment]
![Capture d'écran 2024-06-02 221237](https://github.com/AJTimePyro/Crunchyroll-Account-Checker/assets/171505958/47057625-1636-488e-9f1e-8131f3339276)

**Comment by Certiax** [comment]
![Capture d'écran 2024-06-02 221301](https://github.com/AJTimePyro/Crunchyroll-Account-Checker/assets/171505958/395b4a80-9c90-4874-b7bf-0e71166540af)

**Comment by AJTimePyro** [comment]
Checkout the latest commit, it might have fixed the issue(I am not sure)

**Comment by Certiax** [comment]
I downloaded the lastest release

**Comment by AJTimePyro** [comment]
Release is old, just clone the repo

**Comment by AJTimePyro** [comment]
https://github.com/AJTimePyro/Crunchyroll-Account-Checker?tab=readme-ov-file#installation

**Comment by Certiax** [comment]
And where i'm supposed to verify installion cuz don't work in a cmd

**Comment by AJTimePyro** [comment]
You don't need to verify installation

**Comment by Certiax** [comment]
![Capture d'écran 2024-06-02 230811](https://github.com/AJTimePyro/Crunchyroll-Account-Checker/assets/171505958/d2af9737-1721-4dfd-9598-1d2dd7739293)

**Comment by AJTimePyro** [comment]
Now that's something weird, db.txt might be issue, maybe they are not in utf-8. Can you share small sample of that file?

**Comment by Certiax** [comment]
Nvm it's work lol , im stupid

**Comment by Certiax** [comment]
Btw how does it work without proxies ? , I don't understand

**Comment by AJTimePyro** [comment]
If you don't enable proxy option,  then it will work normally but your ip could be blacklisted.
If you enable proxy option but don't enter any proxy it will fetch proxy from proxyscrape.com

**Comment by Certiax** [comment]
Thx for help and explanations , appreciate

**Comment by Certiax** [comment]
Goat
