### ISSUE TITLE
the checker is working perfectly.. can you add some details if it finds a hit ( working account with subscription)

### ISSUE THREAD

**Issue by AmineZCS** [AJTimePyro/Crunchyroll-Account-Checker#2]
![image](https://user-images.githubusercontent.com/80776723/206905302-75f6def8-a9d9-41e4-91aa-e8e0cac2d94b.png)

**Comment by AmineZCS** [comment]
I mean you don't need to include everything in the capture.. just add 
subscription type.. is free trial? ...

**Comment by AJTimePyro** [comment]
Great Idea, I will add it soon.

**Comment by AJTimePyro** [comment]
Added free trial checker in this [commit](https://github.com/AJTimePyro/Crunchyroll-Account-Checker/commit/05df5437eb225759da127540c43c754d6f785826).
