### ISSUE TITLE
False invalid login credential mark

### ISSUE THREAD

**Issue by guywiththecoolusername** [AJTimePyro/Crunchyroll-Account-Checker#20]
When I try to check the all the accounts it marks all the accounts as invalid while some of them are actually working and not invalid.
I tried reinstalling and trying from a different internet and device but it still doesnt seem to work while it was just working 3-4 days ago.
Please help I'm very new in these kinds of things
edit: Now that i seen the solved issues too i think its similar to #15

**Comment by AJTimePyro** [comment]
It's due to authorization token, I have to find a way to automatically get these tokens, else I have to manually copy from crunchyroll app. It's not a permanent token, it's keep changing after few times. Really a big issue, for now I will just copy token.

**Comment by guywiththecoolusername** [comment]
> It's due to authorization token, I have to find a way to automatically get these tokens, else I have to manually copy from crunchyroll app. It's not a permanent token, it's keep changing after few times. Really a big issue, for now I will just copy token.
 
 Ah, I see. Then can you please share how you get the authorization token?

**Comment by AJTimePyro** [comment]
Well, it's a little difficult. You have to intercept crunchyroll network request. Try to login in crunchyroll (you can try with wrong credentials also), and check the header of api request, there you will find Authorization Token.

Although, I will try to update it in 4-5hours. Also, I will find a way to automate this step.

**Comment by guywiththecoolusername** [comment]
> Well, it's a little difficult. You have to intercept crunchyroll network request. Try to login in crunchyroll (you can try with wrong credentials also), and check the header of api request, there you will find Authorization Token.
> 
> Although, I will try to update it in 4-5hours. Also, I will find a way to automate this step.

Thanks for the sharing, I will try doing this.

**Comment by guywiththecoolusername** [comment]
> Well, it's a little difficult. You have to intercept crunchyroll network request. Try to login in crunchyroll (you can try with wrong credentials also), and check the header of api request, there you will find Authorization Token.
> 
> Although, I will try to update it in 4-5hours. Also, I will find a way to automate this step.

Hi, I did this I got the same result as you did, but even after changing the token the issue persists, I even tried running it in google shell but that didn't work either.
