### ISSUE TITLE
ERRNO 13

### ISSUE THREAD

**Issue by nathanj0rge** [AJTimePyro/Crunchyroll-Account-Checker#23]
Can you help me?
i'm new with this
there:s my error: PermissionError: [Errno 13] Permission denied: 'result//hit.txt'
![2e4710dd-6f3a-4db1-8755-21c772b61cac](https://github.com/user-attachments/assets/d2007f2e-bd9b-469d-bb60-c73454ac3fdb)

**Comment by AJTimePyro** [comment]
that's strange, maybe you already opened hit.txt file in notepad or something, try not to open result files while process is going on. I hate windows for this kind of stupidity.
