### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by farhad2005** [AJTimePyro/Crunchyroll-Account-Checker#6]
It did't even started two or three mail checking and started to say "Too many Requests, Let me take a sleep for 10 seconds."

**Comment by AJTimePyro** [comment]
I even tried proxies(free proxy not paid), but this issue still remains same. If I get any solution for this issue then yeah, I will implement it.

**Comment by farhad2005** [comment]
Thanks for the reply. I will try with some premium proxies by my own
