### ISSUE TITLE
Error in while trying to login HTTP Error 406: Not Acceptable

### ISSUE THREAD

**Issue by amanala** [AJTimePyro/Crunchyroll-Account-Checker#9]
It worked the first time around just fine, but the second time I tried it it got me the following error: **Error in while trying to login HTTP Error 406: Not Acceptable**. Any tips?

**Comment by AJTimePyro** [comment]
Maybe proxy could fix this issue

**Comment by amanala** [comment]
> Maybe proxy could fix this issue

And where do I put the proxies?

**Comment by amanala** [comment]
Nevermind, I'm using VPN every 30 accounts and it's working just fine. Thank you so much for the checker! Maybe in the free time when you're bored you could do a NordVPN one ;ppppp

**Comment by AJTimePyro** [comment]
Lol 30 accounts

**Comment by amanala** [comment]
business lol
